version: '3.8'

services:
  app:
    container_name: go-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:8080'
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      GIN_MODE: "release"
